// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEwwVmwMTh5irBGpQGU2PR7kzUmwATk-k',
    appId: '1:56206815851:web:00e4ccff5157cb8249b72e',
    messagingSenderId: '56206815851',
    projectId: 'agricare-94b91',
    authDomain: 'agricare-94b91.firebaseapp.com',
    storageBucket: 'agricare-94b91.firebasestorage.app',
    measurementId: 'G-FEKPPY1J85',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn5VwzZcxd4d6wDtLhT5C-R7e-fF1q2C0',
    appId: '1:56206815851:android:18f73066b0103e5449b72e',
    messagingSenderId: '56206815851',
    projectId: 'agricare-94b91',
    storageBucket: 'agricare-94b91.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqiUoPOwtlUjL-QI6-L3pgt22Sl2MgBzs',
    appId: '1:56206815851:ios:17f6ff85150264b649b72e',
    messagingSenderId: '56206815851',
    projectId: 'agricare-94b91',
    storageBucket: 'agricare-94b91.firebasestorage.app',
    iosBundleId: 'com.example.agricare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqiUoPOwtlUjL-QI6-L3pgt22Sl2MgBzs',
    appId: '1:56206815851:ios:17f6ff85150264b649b72e',
    messagingSenderId: '56206815851',
    projectId: 'agricare-94b91',
    storageBucket: 'agricare-94b91.firebasestorage.app',
    iosBundleId: 'com.example.agricare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEwwVmwMTh5irBGpQGU2PR7kzUmwATk-k',
    appId: '1:56206815851:web:fdf52313ac722bf849b72e',
    messagingSenderId: '56206815851',
    projectId: 'agricare-94b91',
    authDomain: 'agricare-94b91.firebaseapp.com',
    storageBucket: 'agricare-94b91.firebasestorage.app',
    measurementId: 'G-W9JCQS97W9',
  );
}
